[0;33m--- WARNING: Serial ports accessed as /dev/tty.* will hang gdb if launched.[0m
[0;33m--- Using /dev/cu.usbserial-DU0CUKCC instead...[0m
[0;33m--- esp-idf-monitor 1.3.4 on /dev/cu.usbserial-DU0CUKCC 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33mStack dump detected[0m
[0;33m0x4080355c: s_slave_isr_handle_default at /Users/naichenzhao/esp/esp-idf/components/esp_driver_i2c/i2c_slave.c:155
[0m
[0;33m0x40800cae: shared_intr_isr at /Users/naichenzhao/esp/esp-idf/components/esp_hw_support/intr_alloc.c:450
[0m
[0;33m0x408074c8: rtos_int_enter at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/portasm.S:314
[0m
[0;33m0x40800001: _vector_table at ??:?
[0m
[1;31mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/Users/naichenzhao/Desktop/SLICE/SLICE-Spider/Firmware/V1/spider_sub/build/app-template.elf', '-ex', 'target remote | "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/bin/python" -m "esp_idf_panic_decoder" --target esp32c6 "/var/folders/2h/lww79zv53b510qlyvytqnvq40000gn/T/tmp5a63z0c0"', '-ex', 'bt']' returned non-zero exit status 1.
b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n  File "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 281, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 134, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote connection closed\nNo stack.\n'

[0m
[0;33m0x4001975a: software_reset_cpu in ROM
[0m
[0;33mStack dump detected[0m
[0;33m0x4080355c: s_slave_isr_handle_default at /Users/naichenzhao/esp/esp-idf/components/esp_driver_i2c/i2c_slave.c:155
[0m
[0;33m0x40800cae: shared_intr_isr at /Users/naichenzhao/esp/esp-idf/components/esp_hw_support/intr_alloc.c:450
[0m
[0;33m0x408074c8: rtos_int_enter at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/portasm.S:314
[0m
[0;33m0x40800001: _vector_table at ??:?
[0m
[0;33m
Backtrace:

[0m
[0;33m0x4001975a: software_reset_cpu in ROM
[0m
[0;33mStack dump detected[0m
[0;33m0x4080355c: s_slave_isr_handle_default at /Users/naichenzhao/esp/esp-idf/components/esp_driver_i2c/i2c_slave.c:155
[0m
[0;33m0x40800cae: shared_intr_isr at /Users/naichenzhao/esp/esp-idf/components/esp_hw_support/intr_alloc.c:450
[0m
[0;33m0x408074c8: rtos_int_enter at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/portasm.S:314
[0m
[0;33m0x40800001: _vector_table at ??:?
[0m
[0;33m
Backtrace:

[0m
[0;33m0x4001975a: software_reset_cpu in ROM
[0m
[0m
